# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-10 16:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='vote_access',
            field=models.CharField(choices=[('PUBLIC', 'PUBLIC'), ('DEFAULT', 'DEFAULT'), ('PROTECTED', 'PROTECTED'), ('PRIVATE', 'PRIVATE')], max_length=3),
        ),
    ]
