# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-10 18:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0002_auto_20160510_2209'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='total_votes',
            field=models.BigIntegerField(default=0),
        ),
    ]
